### PR TITLE
Clean skeleton

### PR DESCRIPTION
**Pull request by chanar**
Sample pull request

### CODE REVIEW

**Comment by lkraav** [comment]
Need to upgrade your GH-fu here. Nobody merges bundled randomish looking changes.

One PR per concept, and each PR needs to clearly explain its purpose, what problem it is solving.

Looking over the commit diff, this does not look mergeable, since I have no idea what happened here.

**Comment by chanar** [comment]
I just made a sample pull request to share the merge diff. There is sample
pull request written to description as well.

**Comment by lkraav** [comment]
> I just made a sample pull request to share the merge diff. There is sample pull request written to description as well.

Not sure we're understanding each other. I'm not sure how either of the above sentences help clarity?

"I have no idea what happened here." means "I see the diff, but most of the action taken there seems to make no sense without detailed explanation".

**Comment by chanar** [comment]
What's not understsandable? I have removed the demo related stuff (folder and bower dependency), also changed the paths to properly point to /bower_components/ source.

Also, removed the material theme folder and the bower dependency.

iron-component-page was also purely for demo purpose and I replaced this with the current skeleton component cxl-element. 

I also added sample click function to the skeleton component. 
this.$.triggerButton.addEventListener('click', e => {this._triggerPrivateFunction(e)});

Nothing else I think.

**Comment by lkraav** [comment]
> I have removed the demo related stuff (folder and bower dependency)

But we're planning to actively use their demo framework to demonstrate our work in the team. What made you think this part is expendable?

**Comment by chanar** [comment]
I pushed polymer 2 cxl-app-layout to https://github.com/conversionxl/cxl-app-layout/tree/cxl-app-layout

If you git clone, npm install and bower install and run polymer serv --open you can see the result because index.html serves this purpose (take a look at index.html).

If I'm not wrong, demo is for shareable components so you can show the demo in online web-components directory (or git clone and see how it looks). We are doing team inner components and we  don't have the need to work on demo styles to make the demo look something good. Similar to cxl-sidebar-collapse-item what I'm working on. It's just collapsible header with collapsible items that only makes sense when incorporated to cxl-app-layout.

**Comment by lkraav** [comment]
Housekeeping.

**Pull request closed without merging**
